/** Punto de entrada del núcleo: la UI importa desde aquí, nunca de rutas internas. */
export * from './types'
export * from './constants'
export { kvStore } from './storage/kv-store'
export * from './storage/schema'
export { libraryRepository, type LibrarySnapshot, type ImportSummary } from './storage/library-repository'
export * from './filters/apply-filters'
export * from './random/rng'
export * from './random/spin'
export * from './modes/selection-modes'
export * from './stats/compute-stats'
export * from './importers/types'
export * from './importers/registry'
export * from './importers/file-import'
export * from './importers/sample-library'
export * from './messaging/messages'
export * from './discover/types'
export * from './discover/client'
